name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Clone repo
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: mrbraiant
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        
      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
